metadata:
    name: spark-pipeline
sparkApp:
  spec:
    type: Java
    image: "docker-registry-PLACEHOLDER/repository/regression-test-spark-worker-docker:latest"
    mainClass: org.test.SparkPipelineDriver
    mainApplicationFile: "local:///opt/spark/jobs/pipelines/spark-pipeline.jar"
    deps:
      packages:
        - mysql:mysql-connector-java:8.0.30
        - org.apache.hadoop:hadoop-aws:3.3.4
        - com.amazonaws:aws-java-sdk-bundle:1.12.262
        - io.delta:delta-spark_2.12:3.2.1
        - io.delta:delta-storage:3.2.1
      excludePackages: []
    hadoopConf:
      fs.s3a.fast.upload: "true"
      fs.s3a.path.style: "true"
    driver:
      cores: 1
      coreLimit: "1200m"
      memory: "2048m"
      # Setup these secret key references within your SealedSecret 
      envFrom:
        - secretRef:
            name: remote-auth-config
      env:
        - name: KRAUSENING_BASE
          value: /opt/spark/krausening/base
        - name: "s3TestModelOne_FS_OVERRIDES"
          value: '{
            "jclouds.endpoint": "http://s3-local:4566",
            "jclouds.s3.virtual-host-buckets": "false"
          }'
        - name: "s3TestModelOne_FS_PROVIDER"
          value: "s3"
        - name: "s3TestModelOne_FS_ACCESS_KEY_ID"
          valueFrom:
            secretKeyRef:
              name: remote-auth-config
              key: AWS_ACCESS_KEY_ID
        - name: "s3TestModelOne_FS_SECRET_ACCESS_KEY"
          valueFrom:
            secretKeyRef:
              name: remote-auth-config
              key: AWS_SECRET_ACCESS_KEY
        - name: ENABLE_LINEAGE
          value: "true"
      javaOptions: "-DKRAUSENING_BASE=/opt/spark/krausening/base"
    executor:
      cores: 1
      memory: "4096m"
      envFrom:
        - secretRef:
            name: remote-auth-config
      env:
        - name: KRAUSENING_BASE
          value: /opt/spark/krausening/base
        - name: ENABLE_LINEAGE
          value: "true"
      javaOptions: "-DKRAUSENING_BASE=/opt/spark/krausening/base"
